#!/bin/bash
nrniv -nogui ParameterInstance1.hoc
nrniv -nogui ParameterInstance2.hoc
nrniv -nogui ParameterInstance3.hoc
nrniv -nogui ParameterInstance4.hoc
nrniv -nogui ParameterInstance5.hoc
nrniv -nogui ParameterInstance6.hoc
nrniv -nogui ParameterInstance7.hoc
nrniv -nogui ParameterInstance8.hoc
nrniv -nogui ParameterInstance9.hoc
nrniv -nogui ParameterInstance10.hoc
nrniv -nogui ParameterInstance11.hoc
nrniv -nogui ParameterInstance12.hoc
nrniv -nogui ParameterInstance13.hoc
nrniv -nogui ParameterInstance14.hoc
nrniv -nogui ParameterInstance15.hoc
nrniv -nogui ParameterInstance16.hoc
nrniv -nogui ParameterInstance17.hoc
nrniv -nogui ParameterInstance18.hoc
nrniv -nogui ParameterInstance19.hoc
nrniv -nogui ParameterInstance20.hoc
nrniv -nogui ParameterInstance21.hoc
nrniv -nogui ParameterInstance22.hoc
nrniv -nogui ParameterInstance23.hoc
nrniv -nogui ParameterInstance24.hoc
nrniv -nogui ParameterInstance25.hoc
nrniv -nogui ParameterInstance26.hoc
nrniv -nogui ParameterInstance27.hoc
nrniv -nogui ParameterInstance28.hoc
nrniv -nogui ParameterInstance29.hoc
nrniv -nogui ParameterInstance30.hoc
nrniv -nogui ParameterInstance31.hoc
nrniv -nogui ParameterInstance32.hoc
nrniv -nogui ParameterInstance33.hoc
nrniv -nogui ParameterInstance34.hoc
nrniv -nogui ParameterInstance35.hoc
nrniv -nogui ParameterInstance36.hoc
nrniv -nogui ParameterInstance37.hoc
nrniv -nogui ParameterInstance38.hoc
nrniv -nogui ParameterInstance39.hoc
nrniv -nogui ParameterInstance40.hoc

