#!/bin/bash
nrniv -nogui ParameterInstance121.hoc
nrniv -nogui ParameterInstance122.hoc
nrniv -nogui ParameterInstance123.hoc
nrniv -nogui ParameterInstance124.hoc
nrniv -nogui ParameterInstance125.hoc
nrniv -nogui ParameterInstance126.hoc
nrniv -nogui ParameterInstance127.hoc
nrniv -nogui ParameterInstance128.hoc
nrniv -nogui ParameterInstance129.hoc
nrniv -nogui ParameterInstance130.hoc
nrniv -nogui ParameterInstance131.hoc
nrniv -nogui ParameterInstance132.hoc
nrniv -nogui ParameterInstance133.hoc
nrniv -nogui ParameterInstance134.hoc
nrniv -nogui ParameterInstance135.hoc
nrniv -nogui ParameterInstance136.hoc
nrniv -nogui ParameterInstance137.hoc
nrniv -nogui ParameterInstance138.hoc
nrniv -nogui ParameterInstance139.hoc
nrniv -nogui ParameterInstance140.hoc
nrniv -nogui ParameterInstance141.hoc
nrniv -nogui ParameterInstance142.hoc
nrniv -nogui ParameterInstance143.hoc
nrniv -nogui ParameterInstance144.hoc
nrniv -nogui ParameterInstance145.hoc
nrniv -nogui ParameterInstance146.hoc
nrniv -nogui ParameterInstance147.hoc
nrniv -nogui ParameterInstance148.hoc
nrniv -nogui ParameterInstance149.hoc
nrniv -nogui ParameterInstance150.hoc
nrniv -nogui ParameterInstance151.hoc
nrniv -nogui ParameterInstance152.hoc
nrniv -nogui ParameterInstance153.hoc
nrniv -nogui ParameterInstance154.hoc
nrniv -nogui ParameterInstance155.hoc
nrniv -nogui ParameterInstance156.hoc
nrniv -nogui ParameterInstance157.hoc
nrniv -nogui ParameterInstance158.hoc
nrniv -nogui ParameterInstance159.hoc
nrniv -nogui ParameterInstance160.hoc
