#!/bin/bash
nrniv -nogui ParameterInstance81.hoc
nrniv -nogui ParameterInstance82.hoc
nrniv -nogui ParameterInstance83.hoc
nrniv -nogui ParameterInstance84.hoc
nrniv -nogui ParameterInstance85.hoc
nrniv -nogui ParameterInstance86.hoc
nrniv -nogui ParameterInstance87.hoc
nrniv -nogui ParameterInstance88.hoc
nrniv -nogui ParameterInstance89.hoc
nrniv -nogui ParameterInstance90.hoc
nrniv -nogui ParameterInstance91.hoc
nrniv -nogui ParameterInstance92.hoc
nrniv -nogui ParameterInstance93.hoc
nrniv -nogui ParameterInstance94.hoc
nrniv -nogui ParameterInstance95.hoc
nrniv -nogui ParameterInstance96.hoc
nrniv -nogui ParameterInstance97.hoc
nrniv -nogui ParameterInstance98.hoc
nrniv -nogui ParameterInstance99.hoc
nrniv -nogui ParameterInstance100.hoc
nrniv -nogui ParameterInstance101.hoc
nrniv -nogui ParameterInstance102.hoc
nrniv -nogui ParameterInstance103.hoc
nrniv -nogui ParameterInstance104.hoc
nrniv -nogui ParameterInstance105.hoc
nrniv -nogui ParameterInstance106.hoc
nrniv -nogui ParameterInstance107.hoc
nrniv -nogui ParameterInstance108.hoc
nrniv -nogui ParameterInstance109.hoc
nrniv -nogui ParameterInstance110.hoc
nrniv -nogui ParameterInstance111.hoc
nrniv -nogui ParameterInstance112.hoc
nrniv -nogui ParameterInstance113.hoc
nrniv -nogui ParameterInstance114.hoc
nrniv -nogui ParameterInstance115.hoc
nrniv -nogui ParameterInstance116.hoc
nrniv -nogui ParameterInstance117.hoc
nrniv -nogui ParameterInstance118.hoc
nrniv -nogui ParameterInstance119.hoc
nrniv -nogui ParameterInstance120.hoc
