#!/bin/bash
nrniv -nogui ParameterInstance241.hoc
nrniv -nogui ParameterInstance242.hoc
nrniv -nogui ParameterInstance243.hoc
nrniv -nogui ParameterInstance244.hoc
nrniv -nogui ParameterInstance245.hoc
nrniv -nogui ParameterInstance246.hoc
nrniv -nogui ParameterInstance247.hoc
nrniv -nogui ParameterInstance248.hoc
nrniv -nogui ParameterInstance249.hoc
nrniv -nogui ParameterInstance250.hoc
nrniv -nogui ParameterInstance251.hoc
nrniv -nogui ParameterInstance252.hoc
nrniv -nogui ParameterInstance253.hoc
nrniv -nogui ParameterInstance254.hoc
nrniv -nogui ParameterInstance255.hoc
nrniv -nogui ParameterInstance256.hoc
nrniv -nogui ParameterInstance257.hoc
nrniv -nogui ParameterInstance258.hoc
nrniv -nogui ParameterInstance259.hoc
nrniv -nogui ParameterInstance260.hoc
nrniv -nogui ParameterInstance261.hoc
nrniv -nogui ParameterInstance262.hoc
nrniv -nogui ParameterInstance263.hoc
nrniv -nogui ParameterInstance264.hoc
nrniv -nogui ParameterInstance265.hoc
nrniv -nogui ParameterInstance266.hoc
nrniv -nogui ParameterInstance267.hoc
nrniv -nogui ParameterInstance268.hoc
nrniv -nogui ParameterInstance269.hoc
nrniv -nogui ParameterInstance270.hoc
nrniv -nogui ParameterInstance271.hoc
nrniv -nogui ParameterInstance272.hoc
nrniv -nogui ParameterInstance273.hoc
nrniv -nogui ParameterInstance274.hoc
nrniv -nogui ParameterInstance275.hoc
nrniv -nogui ParameterInstance276.hoc
nrniv -nogui ParameterInstance277.hoc
nrniv -nogui ParameterInstance278.hoc
nrniv -nogui ParameterInstance279.hoc
nrniv -nogui ParameterInstance280.hoc
