#!/bin/bash
nrniv -nogui ParameterInstance201.hoc
nrniv -nogui ParameterInstance202.hoc
nrniv -nogui ParameterInstance203.hoc
nrniv -nogui ParameterInstance204.hoc
nrniv -nogui ParameterInstance205.hoc
nrniv -nogui ParameterInstance206.hoc
nrniv -nogui ParameterInstance207.hoc
nrniv -nogui ParameterInstance208.hoc
nrniv -nogui ParameterInstance209.hoc
nrniv -nogui ParameterInstance210.hoc
nrniv -nogui ParameterInstance211.hoc
nrniv -nogui ParameterInstance212.hoc
nrniv -nogui ParameterInstance213.hoc
nrniv -nogui ParameterInstance214.hoc
nrniv -nogui ParameterInstance215.hoc
nrniv -nogui ParameterInstance216.hoc
nrniv -nogui ParameterInstance217.hoc
nrniv -nogui ParameterInstance218.hoc
nrniv -nogui ParameterInstance219.hoc
nrniv -nogui ParameterInstance220.hoc
nrniv -nogui ParameterInstance221.hoc
nrniv -nogui ParameterInstance222.hoc
nrniv -nogui ParameterInstance223.hoc
nrniv -nogui ParameterInstance224.hoc
nrniv -nogui ParameterInstance225.hoc
nrniv -nogui ParameterInstance226.hoc
nrniv -nogui ParameterInstance227.hoc
nrniv -nogui ParameterInstance228.hoc
nrniv -nogui ParameterInstance229.hoc
nrniv -nogui ParameterInstance230.hoc
nrniv -nogui ParameterInstance231.hoc
nrniv -nogui ParameterInstance232.hoc
nrniv -nogui ParameterInstance233.hoc
nrniv -nogui ParameterInstance234.hoc
nrniv -nogui ParameterInstance235.hoc
nrniv -nogui ParameterInstance236.hoc
nrniv -nogui ParameterInstance237.hoc
nrniv -nogui ParameterInstance238.hoc
nrniv -nogui ParameterInstance239.hoc
nrniv -nogui ParameterInstance240.hoc
