#!/bin/bash
nrniv -nogui ParameterInstance41.hoc
nrniv -nogui ParameterInstance42.hoc
nrniv -nogui ParameterInstance43.hoc
nrniv -nogui ParameterInstance44.hoc
nrniv -nogui ParameterInstance45.hoc
nrniv -nogui ParameterInstance46.hoc
nrniv -nogui ParameterInstance47.hoc
nrniv -nogui ParameterInstance48.hoc
nrniv -nogui ParameterInstance49.hoc
nrniv -nogui ParameterInstance50.hoc
nrniv -nogui ParameterInstance51.hoc
nrniv -nogui ParameterInstance52.hoc
nrniv -nogui ParameterInstance53.hoc
nrniv -nogui ParameterInstance54.hoc
nrniv -nogui ParameterInstance55.hoc
nrniv -nogui ParameterInstance56.hoc
nrniv -nogui ParameterInstance57.hoc
nrniv -nogui ParameterInstance58.hoc
nrniv -nogui ParameterInstance59.hoc
nrniv -nogui ParameterInstance60.hoc
nrniv -nogui ParameterInstance61.hoc
nrniv -nogui ParameterInstance62.hoc
nrniv -nogui ParameterInstance63.hoc
nrniv -nogui ParameterInstance64.hoc
nrniv -nogui ParameterInstance65.hoc
nrniv -nogui ParameterInstance66.hoc
nrniv -nogui ParameterInstance67.hoc
nrniv -nogui ParameterInstance68.hoc
nrniv -nogui ParameterInstance69.hoc
nrniv -nogui ParameterInstance70.hoc
nrniv -nogui ParameterInstance71.hoc
nrniv -nogui ParameterInstance72.hoc
nrniv -nogui ParameterInstance73.hoc
nrniv -nogui ParameterInstance74.hoc
nrniv -nogui ParameterInstance75.hoc
nrniv -nogui ParameterInstance76.hoc
nrniv -nogui ParameterInstance77.hoc
nrniv -nogui ParameterInstance78.hoc
nrniv -nogui ParameterInstance79.hoc
nrniv -nogui ParameterInstance80.hoc

