#!/bin/bash
nrniv -nogui ParameterInstance161.hoc
nrniv -nogui ParameterInstance162.hoc
nrniv -nogui ParameterInstance163.hoc
nrniv -nogui ParameterInstance164.hoc
nrniv -nogui ParameterInstance165.hoc
nrniv -nogui ParameterInstance166.hoc
nrniv -nogui ParameterInstance167.hoc
nrniv -nogui ParameterInstance168.hoc
nrniv -nogui ParameterInstance169.hoc
nrniv -nogui ParameterInstance170.hoc
nrniv -nogui ParameterInstance171.hoc
nrniv -nogui ParameterInstance172.hoc
nrniv -nogui ParameterInstance173.hoc
nrniv -nogui ParameterInstance174.hoc
nrniv -nogui ParameterInstance175.hoc
nrniv -nogui ParameterInstance176.hoc
nrniv -nogui ParameterInstance177.hoc
nrniv -nogui ParameterInstance178.hoc
nrniv -nogui ParameterInstance179.hoc
nrniv -nogui ParameterInstance180.hoc
nrniv -nogui ParameterInstance181.hoc
nrniv -nogui ParameterInstance182.hoc
nrniv -nogui ParameterInstance183.hoc
nrniv -nogui ParameterInstance184.hoc
nrniv -nogui ParameterInstance185.hoc
nrniv -nogui ParameterInstance186.hoc
nrniv -nogui ParameterInstance187.hoc
nrniv -nogui ParameterInstance188.hoc
nrniv -nogui ParameterInstance189.hoc
nrniv -nogui ParameterInstance190.hoc
nrniv -nogui ParameterInstance191.hoc
nrniv -nogui ParameterInstance192.hoc
nrniv -nogui ParameterInstance193.hoc
nrniv -nogui ParameterInstance194.hoc
nrniv -nogui ParameterInstance195.hoc
nrniv -nogui ParameterInstance196.hoc
nrniv -nogui ParameterInstance197.hoc
nrniv -nogui ParameterInstance198.hoc
nrniv -nogui ParameterInstance199.hoc
nrniv -nogui ParameterInstance200.hoc

