#!/bin/bash
nrniv -nogui ParameterInstance281.hoc
nrniv -nogui ParameterInstance282.hoc
nrniv -nogui ParameterInstance283.hoc
nrniv -nogui ParameterInstance284.hoc
nrniv -nogui ParameterInstance285.hoc
nrniv -nogui ParameterInstance286.hoc
nrniv -nogui ParameterInstance287.hoc
nrniv -nogui ParameterInstance288.hoc
nrniv -nogui ParameterInstance289.hoc
nrniv -nogui ParameterInstance290.hoc
nrniv -nogui ParameterInstance291.hoc
nrniv -nogui ParameterInstance292.hoc
nrniv -nogui ParameterInstance293.hoc
nrniv -nogui ParameterInstance294.hoc
nrniv -nogui ParameterInstance295.hoc
nrniv -nogui ParameterInstance296.hoc
nrniv -nogui ParameterInstance297.hoc
nrniv -nogui ParameterInstance298.hoc
nrniv -nogui ParameterInstance299.hoc
nrniv -nogui ParameterInstance300.hoc
nrniv -nogui ParameterInstance301.hoc
nrniv -nogui ParameterInstance302.hoc
nrniv -nogui ParameterInstance303.hoc
nrniv -nogui ParameterInstance304.hoc
nrniv -nogui ParameterInstance305.hoc
nrniv -nogui ParameterInstance306.hoc
nrniv -nogui ParameterInstance307.hoc
nrniv -nogui ParameterInstance308.hoc
nrniv -nogui ParameterInstance309.hoc
nrniv -nogui ParameterInstance310.hoc
nrniv -nogui ParameterInstance311.hoc
nrniv -nogui ParameterInstance312.hoc
nrniv -nogui ParameterInstance313.hoc
nrniv -nogui ParameterInstance314.hoc
nrniv -nogui ParameterInstance315.hoc
nrniv -nogui ParameterInstance316.hoc
nrniv -nogui ParameterInstance317.hoc
nrniv -nogui ParameterInstance318.hoc
nrniv -nogui ParameterInstance319.hoc
nrniv -nogui ParameterInstance320.hoc
